.PHONY: clean All

All:
	@echo "----------Building project:[ bisection - Debug ]----------"
	@cd "bisection" && "$(MAKE)" -f  "bisection.mk"
clean:
	@echo "----------Cleaning project:[ bisection - Debug ]----------"
	@cd "bisection" && "$(MAKE)" -f  "bisection.mk" clean
