.PHONY: clean All

All:
	@echo "----------Building project:[ sor - Debug ]----------"
	@cd "sor" && "$(MAKE)" -f  "sor.mk"
clean:
	@echo "----------Cleaning project:[ sor - Debug ]----------"
	@cd "sor" && "$(MAKE)" -f  "sor.mk" clean
